java_library(
    name = "grpc_server_runner",
    visibility = ["//visibility:public"],
    srcs = ["GrpcServerRunner.java"],
    deps = [
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_grpc_grpc_api",
    ],
)

java_library(
    name = "grpc_server_runner_module",
    visibility = ["//visibility:public"],
    srcs = ["GrpcServerRunnerModule.java"],
    deps = [
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_grpc_grpc_api",
    ],
)
